// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgljmitwuauiykkzodhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnbGptaXR3dWF1aXlra3pvZGhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjcyMzYsImV4cCI6MjA3MTU0MzIzNn0.xJXu2YpJv6luVfWeXWINRdruWBBHmuWdaJvQpGJCdZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});